// Matilda
package game;

import util.HangmanDictionary;

// The HangmanGameAutoGuesser class plays the Hangman game with a guesses generated by the computer according to a smart algorithm,
public class HangmanGameAutoGuesser extends HangmanGame {
	
	// Constants for AutoGuesser.
	private static final String LETTERS_ORDERED_BY_FREQUENCY = "etaoinshrldcumfpgwybvkxjqz";

	// Fields for AutoGuesser. 
	private int myIndex;
	private String myLetters;
	
	// Constructs a HangmanGameAutoGusser.
	public HangmanGameAutoGuesser(HangmanDictionary dictionary, int wordLength, int numGuesses,  String userChoice) {
		super(dictionary, wordLength, numGuesses, userChoice);
		myIndex = 0;
		myLetters = LETTERS_ORDERED_BY_FREQUENCY;
	}
	
	// Plays one complete game with an auto guesser. 
	public void play () {
		boolean gameOver = false;
        while (!gameOver) {
            printStatus();

            Character guess = myLetters.charAt(myIndex++);
            myGuesser.makeGuess(guess);
            gameOver = isGameOver(gameOver);
        }
        myExecutioner.printSecretWordMessage();
	}
}
